import React from 'react';

const DataDisplay = ({ text }) => (
  <div className="card">
    <p>{text || 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, diam vitae lobortis cursus, massa nulla tincidunt enim, imperdiet porta nisi quam sed quam. Vestibulum facilisis justo aliquam magna rutrum ornare. Praesent accumsan lectus in quam mollis elementum eu et odio. Etiam vel lectus libero. Nullam ligula leo, volutpat et ultrices a, blandit non libero. Nam a felis et erat lacinia posuere ac ut diam. Aliquam erat volutpat. Donec suscipit ut nisl ac fermentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec et dui aliquam, porttitor enim ut, tempus mauris. Curabitur commodo arcu et lectus fermentum, sed auctor mauris tincidunt. Phasellus sed augue euismod, ultricies sem ac, consectetur ante. Suspendisse imperdiet gravida arcu, vitae tempor leo lobortis in. Phasellus iaculis eu turpis vitae ultricies. Morbi vitae sapien suscipit nibh tincidunt ultrices et fringilla mauris. Nulla vulputate tellus arcu, non rutrum ipsum pellentesque at. Fusce euismod sed ipsum id auctor. Vivamus dapibus justo sit amet nisi facilisis, non dictum lectus porta. Fusce molestie eget neque at convallis. Curabitur at ligula lectus. Donec condimentum egestas consectetur. Nam iaculis ullamcorper hendrerit. Integer placerat erat nisl. Phasellus porttitor porttitor risus, interdum consectetur diam dictum vel. Nullam aliquet dapibus auctor. Aenean interdum odio nisl, vel viverra mauris blandit et. Donec pharetra purus vitae libero gravida finibus. Sed vehicula quam id nunc fringilla ullamcorper. Fusce feugiat justo id suscipit porta. Aliquam consectetur lorem quis ex ultrices, sed tempus turpis vehicula. Mauris vel leo nec tortor ornare porttitor sed et orci. Maecenas ut ullamcorper dolor. Aenean porttitor urna et lectus ullamcorper ullamcorper. Etiam ut porta nibh. Quisque imperdiet nisl a ex malesuada, a convallis nisi iaculis.'}</p>
  </div>
);

export default DataDisplay;
